### ISSUE TITLE
Use a custom user agent in the WebView

### ISSUE THREAD

**Issue by Andreascoolcrafts** [danielsaidi/WebViewKit#2]
Hi, 
sorry for the bad question, but is it possible to use a custom user agent in the WebView?
Thanks.

**Comment by danielsaidi** [comment]
Hi @Andreascoolcrafts 

Sure, it's possible with `WebView`:

```
WebView(url: url) { webView in
    // Configure the web view in any way you like
    // For instance, let's set a custom user agent.
    webView.customUserAgent = "foo bar"
}
```

It's however not possible with `SafariWebVew`.

**Comment by Andreascoolcrafts** [comment]
Thank you very much, now everything works on my application!

**Comment by danielsaidi** [comment]
Amazing, happy to hear that! 🎉
