### ISSUE TITLE
Apple.com toolbar in safe area

### ISSUE THREAD

**Issue by aehlke** [danielsaidi/WebViewKit#4]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/71601/224906252-bf4d25ee-da97-40bc-8d54-5903bac6808e.png">

(I don't currently use this library but wanted to let you know about this issue.)

**Comment by danielsaidi** [comment]
Thank you, I have updated the demo app!

**Comment by aehlke** [comment]
I've learned that Apple solves this in Safari via `_obscuredInsets`

**Comment by danielsaidi** [comment]
Ok, that's interesting to know! In this case, I just added a navigation view to the demo :)

**Comment by aehlke** [comment]
_obscuredInsets allows you to have `regularMaterial` type overlays on top and bottom

I also suggest looking at the behavior of apple.com on landscape, even with your new navigation view approach - I think you'll find issues there too that only _obscuredInsets can likely solve (empty margins on left and right, or page elements too far into the left/right margins)
