### ISSUE TITLE
How do you suppress the WebViewKit pane on the right?

### ISSUE THREAD

**Issue by curtcox** [danielsaidi/WebViewKit#5]
I would like to suppress the empty WebViewKit pane on the right side.
Please consider adding how to do this to the documentation.

**Comment by danielsaidi** [comment]
Hi @curtcox 

I'm not sure which pane you mean? Can you provide an example?

**Comment by curtcox** [comment]
<img width="595" alt="WebViewKit" src="https://github.com/danielsaidi/WebViewKit/assets/353568/de04f48e-d7de-45c7-88b6-6bc22cdfd1b6">

I'm talking about the right half of the image above. 
When I launch on MacOS the pane is empty. It can be resized so that it is almost entirely, but not quite, invisible. 
In the example above I have done the following to get content in the pane.
- File >> New Window
- Window >> Merge All Windows

**Comment by danielsaidi** [comment]
Oh, I had accidentally used a `NavigationView` in the macOS demo, which placed the browser in the leading panel. I have pushed a fix for it now.

Thank you for notifying me.
